- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    filename: ietf_interfaces
  tasks:
    - name: GET method (running configuration)
      uri:
        url: 'https://router.labs.conatest.click/restconf/data/ietf-interfaces:interfaces'
        force_basic_auth: yes
        body_format: json
        body: {
          "ietf-interfaces:interfaces": {
            "interface": [{
              "enabled": true,
              "ietf-ip:ipv4": {},
              "ietf-ip:ipv6": {},
              "name": "GigabitEthernet2",
              "type": "iana-if-type:ethernetCsmacd"
            }]
          }
        }
        headers:
          Accept: 'application/yang-data+json,application/yang-data.errors+json'
          Accept-Encoding: 'gzip,deflate'
          Content-Type: 'application/yang-data+json'
        method: GET
        user: conatel
        password: C0n4t3l.
        return_content: yes
        validate_certs: no
      register: output
      failed_when: false
    - debug:
        msg: '{{output}}'