---
# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'

- include_tasks: setup-Fedora.yml
  when: ansible_distribution == 'Fedora'

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: setup-Debian.yml
  when: ansible_distribution == 'Debian'
