- name: Get instance facts
  ec2_instance_facts:
    region: '{{aws_region}}'
    filters:
      'tag:Name': '{{ec2_server_name}}'
  register: ec2

- name: Echo ec2 instance ids
  debug:
    msg: '{{ item.instance_id }}'
  with_items: '{{ ec2.instances }}'

- name: Kill EC2 Instances
  ec2:
    instance_ids: '{{ item.instance_id }}'
    state: absent
    region: us-east-1
    wait: yes
  with_items: '{{ ec2.instances }}'
