# ---
# native_root.yml
#
# Consulta al módulo Cisco-IOS-XE-native por su información principal.
# ---
- hosts: routers
  connection: local
  gather_facts: yes
  vars:
    filter: interface
  tasks:
    - name: Consulta RESTCONF
      uri:
        url: 'https://{{inventory_hostname}}/restconf/data/Cisco-IOS-XE-native:native'
        force_basic_auth: yes
        body_format: json
        headers:
          'Accept': 'application/yang-data+json,application/yang-data.errors+json'
          'Accept-Encoding': 'gzip,deflate'
          'Content-Type': 'application/yang-data+json'
        method: GET
        user: conatel
        password: conatel
        return_content: yes
        validate_certs: no
      register: output
      failed_when: False
    - name: Eliminar la version anterior del archivo
      file:
        path: 'outputs/{{inventory_hostname}}_native.json'
        state: absent
    - name: Guardar los datos en un archivo de texto
      lineinfile:
        dest: 'outputs/{{inventory_hostname}}_native.json'
        line: '{{output["json"] | to_nice_json}}'
        create: yes