version: '3.0'
services:
  base:
    build: ./base/
    image: ansible_base
  master:
    links:
      - base
    build: ./master/
    image: ansible_master
    container_name: master
    hostname: master
    command: ['/usr/sbin/sshd', '-D']
    volumes:
      - ./volume:/var/ans
      - /home/ubuntu/.ssh:/root/.ssh
  host01:
    links:
      - base
      - master
    build: ./host/
    image: ansible_host
    container_name: host01
    hostname: host01
    command: ['/var/run.sh']
    volumes:
      - ./volume:/var/ans
  host02:
    links:
      - base
      - master
      - host01
    image: ansible_host
    container_name: host02
    hostname: host02
    command: ['/var/run.sh']
    volumes:
      - ./volume:/var/ans
  host03:
    links:
      - base
      - master
      - host02
    image: ansible_host
    container_name: host03
    hostname: host03
    command: ['/var/run.sh']
    volumes:
      - ./volume:/var/ans
