version: '3.0'
services:
  base:
    build: ./base/
    image: ansible_base
  controller:
    links:
      - base
    build: ./controller/
    image: ansible_controller
    container_name: controller
    hostname: controller
    ports:
      - "2222:22"
    command: ['/usr/sbin/sshd', '-D']
    working_dir: /root/ansible
    volumes:
      - ./volume:/root/ansible
      - /home/ubuntu/.ssh:/root/.ssh
      - /home/ubuntu/ansible_lab:/root/ansible_lab
  host01:
    links:
      - base
      - controller
    build: ./host/
    image: ansible_host
    container_name: host01
    hostname: host01
    command: ['/var/run.sh']
    working_dir: /root/ansible
    volumes:
      - ./volume:/root/ansible
  host02:
    links:
      - base
      - controller
      - host01
    image: ansible_host
    container_name: host02
    hostname: host02
    command: ['/var/run.sh']
    working_dir: /root/ansible
    volumes:
      - ./volume:/root/ansible
  host03:
    links:
      - base
      - controller
      - host02
    image: ansible_host
    container_name: host03
    hostname: host03
    command: ['/var/run.sh']
    working_dir: /root/ansible
    volumes:
      - ./volume:/root/ansible
