all:
  children:
    localhost:
      hosts: 
        127.0.0.1:
      vars:
        ansible_python_interpreter: /Users/gmonne/.pyenv/shims/python
    master:
      hosts: 
        54.208.249.92:
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_user: ubuntu
        ansible_ssh_private_key_file: secret_vars/key_pair_1
