- name: Change hostname
  hostname:
    name: '{{ ec2_server_name | to_snake_case | replace("#", "") }}'
- name: Change hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1'
    line: '127.0.0.1  {{ ec2_server_name | to_snake_case | replace("#", "")}}'
- name: Fix locale issue
  blockinfile:
    path: /etc/environment
    insertafter: EOF
    content: |
      LC_ALL=en_US.UTF-8
      LANG=en_US.UTF-8
- name: Add custom .bashrc
  blockinfile:
    path: /home/ubuntu/.bashrc
    insertafter: EOF
    content: |
      # Custom alias
      alias cls="clear"

      # Custom Prompt
      function prompt {
        local BLACK="\[\033[0;30m\]"
        local BLACKBOLD="\[\033[1;30m\]"
        local RED="\[\033[0;31m\]"
        local REDBOLD="\[\033[1;31m\]"
        local GREEN="\[\033[0;32m\]"
        local GREENBOLD="\[\033[1;32m\]"
        local YELLOW="\[\033[0;33m\]"
        local YELLOWBOLD="\[\033[1;33m\]"
        local BLUE="\[\033[0;34m\]"
        local BLUEBOLD="\[\033[1;34m\]"
        local PURPLE="\[\033[0;35m\]"
        local PURPLEBOLD="\[\033[1;35m\]"
        local CYAN="\[\033[0;36m\]"
        local CYANBOLD="\[\033[1;36m\]"
        local WHITE="\[\033[0;37m\]"
        local WHITEBOLD="\[\033[1;37m\]"
        local RESETCOLOR="\[\e[00m\]"

        export PS1="\n$RED\u$PURPLE@$(hostname) $GREEN\w $RESETCOLOR$GREENBOLD\$(git branch 2> /dev/null)\n $BLUE[\#] → $RESETCOLOR"
        export PS2=" | → $RESETCOLOR"
      }

      prompt
- name: Install Python 2.7
  apt:
    update_cache: true
    name: python
    state: present
- name: Install PIP
  apt:
    name: python-pip
    state: present
- name: Install docker-py
  pip:
    name: docker-py
    executable: /usr/bin/pip
