---
- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - aws_vpc_up
    - master_ami_up
    - hub_ami_up

- hosts: master
  become: true
  roles:
    - geerlingguy.docker
    - role: configure_master 
      include_vars:
        file: 'secret_vars/pod_1.yml'
