- hosts: master
  become: true
  tasks:
    - name: Sets the python version to 2.7
      set_fact:
        ansible_python_interpreter: /usr/bin/python

    - name: Install docker-compose
      pip:
        name: '{{item}}'
        executable: /usr/bin/pip
      loop:
        - grip
        - markdown
        - jinja2
