---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: add slave1 to group slaves
      add_host:
        name: '10.1.1.100'
        groups: slaves
        slave: 1
        ansible_ssh_private_key_file: secret_vars/key_pair_{{ lab_pod | string }}
        ansible_user: '{{ ec2_server_ansible_ssh_user }}'
        ansible_python_interpreter: '{{ ec2_server_ansible_python_interpreter }}'
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -i secret_vars/key_pair_{{ lab_pod | string }} -q {{ec2_server_ansible_ssh_user}}@{{MASTER_PUBLIC_IP}}"'
  vars_files:
    - ./vars/pod.yml
    - ./secret_vars/pod_1.yml

- hosts: slaves
  become: true
  tasks:
    - include_tasks: ./tasks/slaves_ami_configure.yml
  vars_files:
    - ./vars/pod.yml
