# ---
# get_interface_modules.yml
#
# Obtiene datos de las interfaces utilizando dos módulos distintos
# ---
- hosts: routers
  connection: local
  gather_facts: yes
  tasks:
    - name: 'Descarga de módulos'
      uri:
        url: 'https://{{inventory_hostname}}/restconf/data/{{item}}'
        force_basic_auth: yes
        body_format: json
        headers:
          'Accept': 'application/yang-data+json,application/yang-data.errors+json'
          'Accept-Encoding': 'gzip,deflate'
          'Content-Type': 'application/yang-data+json'
        method: GET
        user: conatel
        password: conatel
        return_content: yes
        validate_certs: no
      register: output
      failed_when: false
      loop:
        - "Cisco-IOS-XE-interfaces-oper:interfaces"
        - "ietf-interfaces:interfaces"
    - name: Almacena los resultados en un archivo de json
      include_role:
        name: ../roles/store_uri_output
      vars:
        output_filename: '{{inventory_hostname}}_interface_modules'