---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: add host to group servers
      add_host:
        name: '{{ ec2.private_ip }}'
        groups: servers
        ansible_ssh_private_key_file: secret_vars/key_pair_{{ lab_pod | string }}
        ansible_user: '{{ ec2_server_ansible_ssh_user }}'
        ansible_python_interpreter: '{{ ec2_server_ansible_python_interpreter }}'
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -i secret_vars/key_pair_{{ lab_pod | string }} -q {{ec2_server_ansible_ssh_user}}@{{MASTER_PUBLIC_IP}}"'
  vars_files:
    - vars.yml

- hosts: servers
  become: true
  tasks:
    - ping:
