# archivo de inventario ./inventory/hosts.yml
all:
  children:
    routers:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ~/.ssh/devops101-labs.pem
        ansible_network_os: ios
        ansible_become: yes
        ansible_become_method: enable
        ansible_connection: network_cli
      hosts:
          hub:
            ansible_host: 10.6.254.254
          spoke01:
            ansible_host: 10.6.201.253
          spoke02:
            ansible_host: 10.6.202.253
      children:
        spokes:
          hosts:
            spoke01:
            spoke02:
    servers:
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_ssh_private_key_file: '~/ansible/master_key'
      hosts:
        host01:
        host02:
        host03:
      children:
        app:
          vars:
            application_name: prod_app
          hosts:
            host01:
            host02:
        db:
          hosts:
            host03:
