- name: Gather VPC facts
  ec2_vpc_net_facts:
    filters:
      'tag:Name': '{{aws_vpc_name}}'
  register: vpc_facts

- name: Set VPC fact
  set_fact:
    net: '{{vpc_facts.vpcs[0]}}'
  when: vpc_facts is defined and vpc_facts.vpcs[0] is defined

# - name: Gather Security Group facts
#   ec2_group_facts:
#     filters:
#       vpc-id: '{{ net.vpc_id }}'
#   register: security_group_facts
#   when: net is defined

# - name: Set Security Group fact
#   set_fact:
#     sg: '{{security_group_facts.security_groups[0]}}'
#   when: item is defined and item.security_groups[0] is defined
#   with_items: '{{security_group_facts.security_groups}}'

# - name: Delete the Security Group
#   ec2_group:
#     group_id: '{{sg.group_id}}'
#     state: absent
#   when: sg is defined

- name: Delete the key pair
  ec2_key:
    name: '{{aws_key_pair_name}}'
    state: absent

- name: Delete the management subnet
  ec2_vpc_subnet:
    state: absent
    vpc_id: '{{ net.vpc_id }}'
    cidr: '{{aws_management_subnet_cidr}}'
  when: net is defined

- name: Delete the IGW
  ec2_vpc_igw:
    vpc_id: '{{ net.vpc_id }}'
    state: absent
    region: '{{aws_region}}'
  register: igw
  when: net is defined

- name: Delete the VPC
  ec2_vpc_net:
    cidr_block: '{{aws_vpc_cidr}}'
    name: '{{ aws_vpc_name }}'
    region: '{{aws_region}}'
    state: absent
