- name: Configurar message-of-the-day 
  hosts: all
  gather_facts: yes
  vars:
    - course_name: "Ansible-101"
  tasks:
    - template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644