# segundo_playbook.yml
- name: Ejemplo de como utilizar la opción 'register'
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Comando shell
      shell: echo Hola
      register: result

    - name: Debug
      debug:
        var: result