# archivo de inventario ./inventory/hosts.yml
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_private_key_file: './master_key'
  hosts:
    host01:
    host02:
    host03:
  children:
    app:
      vars:
        application_name: prod_app
      hosts:
        host01:
        host02:
    db:
      hosts:
        host03: