- name: Launch an instance on EC2
  ec2:
    group_id: '{{ SECURITY_GROUP }}'
    count: 1
    instance_type: 't2.medium'
    image: 'ami-0ac019f4fcb7cb7e6'
    private_ip: '{{aws_management_subnet_class_default}}.100'
    wait: yes
    region: '{{ aws_region }}'
    keypair: '{{ KEY_PAIR }}'
    vpc_subnet_id: '{{ MANAGEMENT_SUBNET }}'
    assign_public_ip: yes
    instance_tags:
      Name: '{{ ec2_server_name }}'
      Pod: '{{lab_pod | string}}'
  register: ec2

- name: Set EC2 fact
  set_fact:
    ec2: '{{ec2.instances[0]}}'

- name: Set DNS records
  route53:
    state: present
    zone: '{{lab_domain}}'
    record: 'master-{{ lab_pod }}.{{lab_domain}}'
    type: A
    value: '{{ ec2.public_ip }}'
    wait: yes
    overwrite: true
  register: dns

- name: 'Create {{ secret_vars_file_name }}.yml file inside the secret_vars directory'
  lineinfile:
    dest: 'secret_vars/{{secret_vars_file_name}}.yml'
    line: '---'
    create: yes

- name: 'Write vpc info to {{secret_vars_file_name}}.yml file inside the secret_vars directory'
  lineinfile:
    dest: 'secret_vars/{{secret_vars_file_name}}.yml'
    regexp: '^{{ item.regexp | upper }}'
    line: "{{ item.regexp | upper }}: {{ '\"' + item.line + '\"' }}"
  with_items:
    - { regexp: 'master_public_ip', line: '{{ ec2.public_ip }}' }
    - { regexp: 'master_public_dns', line: 'master-{{ lab_pod }}.{{lab_domain}}'}

- include_vars: 'secret_vars/{{ secret_vars_file_name }}.yml'

- name: add host to group '{{ec2_server_group}}'
  add_host:
    name: '{{ ec2.public_ip }}'
    groups: '{{ec2_server_group}}'
    ansible_ssh_private_key_file: secret_vars/key_pair_{{ lab_pod | string }}
    ansible_user: '{{ ec2_server_ansible_ssh_user }}'
    ansible_python_interpreter: '{{ ec2_server_ansible_python_interpreter }}'
