- name: Launch the HUB router
  ec2:
    group_id: '{{ SECURITY_GROUP }}'
    count: 1
    instance_type: 't2.medium'
    image: 'ami-062f4179'
    wait: yes
    region: '{{ aws_region }}'
    keypair: '{{ KEY_PAIR }}'
    vpc_subnet_id: '{{ MANAGEMENT_SUBNET }}'
    assign_public_ip: no
    instance_tags:
      Name: '{{ ec2_server_name }}'
      Pod: '{{lab_pod | string}}'
  register: hub

- name: Set EC2 fact
  set_fact:
    hub: '{{hub.instances[0]}}'

- name: Set DNS records
  route53:
    state: present
    zone: conatest.click
    record: '{{ hub_dns_record }}'
    type: A
    value: '{{ hub.private_ip }}'
    wait: yes
    overwrite: true
  register: dns

- name: 'Create {{ secret_vars_file_name }}.yml file inside the secret_vars directory'
  lineinfile:
    dest: 'secret_vars/{{secret_vars_file_name}}.yml'
    line: '---'
    create: yes

- name: 'Write vpc info to {{secret_vars_file_name}}.yml file inside the secret_vars directory'
  lineinfile:
    dest: 'secret_vars/{{secret_vars_file_name}}.yml'
    regexp: '^{{ item.regexp | upper }}'
    line: "{{ item.regexp | upper }}: {{ '\"' + item.line + '\"' }}"
  with_items:
    - { regexp: 'hub_private_ip', line: '{{ hub.public_ip }}' }
    - { regexp: 'hub_public_dns', line: '{{ hub_dns_record }}' }

- include_vars: "secret_vars/{{ secret_vars_file_name }}.yml"

- name: add host to group 'master'
  add_host:
    name: '{{ hub.public_ip }}'
    groups: '{{ec2_server_group}}'
    ansible_ssh_private_key_file: secret_vars/key_pair_{{ lab_pod | string }}
    ansible_user: '{{ ec2_server_ansible_ssh_user }}'
    ansible_network_os: ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_connection: network_cli
    ansible_become_pass:
